In [1]:
from src.modeller import entrenar, predecir
from src.logger import LoggerService

In [2]:
logger = LoggerService()

Ruta de logs configurada: src/logs
Directorio de logs creado/verificado en: src/logs
Archivo de log configurado: src/logs/log_2025-05-25.txt
Logger configurado exitosamente

In [3]:
entrenar(logger)

,id,timestamp,open,high,low,close,volume,adjclose,date,symbol,...,rsi,target,sma_ratio,sma_cross,volatility_ratio,volume_ratio,rsi_oversold,rsi_overbought,returns_2d,returns_5d
0,50,1710336600,143.050003,143.229996,141.369995,142.139999,12923100,139.611938,2024-03-13 09:30:00+00:00,TSM,...,62.801178,0,0.060996,1,NaN,NaN,0,0,NaN,NaN
1,51,1710423000,142.610001,143.100006,139.020004,139.619995,14961900,137.136749,2024-03-14 09:30:00+00:00,TSM,...,59.499155,0,0.038175,1,NaN,NaN,0,0,NaN,NaN
2,52,1710509400,135.440002,137.699997,134.630005,136.979996,22733000,134.543701,2024-03-15 09:30:00+00:00,TSM,...,55.801610,0,0.015543,1,NaN,NaN,0,0,-0.036302,NaN
3,53,1710768600,140.179993,141.539993,136.610001,136.639999,14732900,134.754761,2024-03-18 09:30:00+00:00,TSM,...,57.604391,0,0.009300,1,NaN,NaN,0,0,-0.021344,NaN
4,54,1710855000,135.300003,136.270004,133.029999,134.869995,17341100,133.009186,2024-03-19 09:30:00+00:00,TSM,...,57.001311,0,-0.007272,1,NaN,NaN,0,0,-0.015404,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,346,1747684801,189.000000,193.500000,188.811005,193.500000,8935823,193.500000,2025-05-19 16:00:01+00:00,TSM,...,81.862109,0,0.100154,1,0.690063,0.641174,0,1,-0.003707,0.034870
297,347,1747771202,191.800003,193.720001,190.809998,193.449997,7039161,193.449997,2025-05-20 16:00:02+00:00,TSM,...,80.843708,0,0.086877,1,0.697828,0.515494,0,1,-0.003965,-0.002784
298,348,1747857602,193.100006,195.259995,190.529999,191.759995,6647988,191.759995,2025-05-21 16:00:02+00:00,TSM,...,74.385241,0,0.067204,1,0.676790,0.507318,0,1,-0.008992,-0.015404
299,349,1747944002,191.339996,196.830002,191.360001,196.190002,11059927,196.190002,2025-05-22 16:00:02+00:00,TSM,...,72.907074,1,0.082219,1,0.646455,0.869551,0,1,0.014164,0.010143
300,350,1748007000,192.020004,192.800003,190.029999,191.979996,9394700,191.979996,2025-05-23 09:30:00+00:00,TSM,...,70.371338,0,0.051202,1,0.682272,0.754223,0,1,0.001147,-0.011533

In [4]:
predecir(logger)

{'prediccion': 0,
 'probabilidad': 0.004816742148250341,
 'threshold': 0.49999999999999994,
 'fecha': Timestamp('2025-05-23 09:30:00+0000', tz='UTC'),
 'precio_actual': 191.97999572753903,
 'metricas_modelo': {'rmse': 0.30010052228676876,
  'mae': 0.15982674062252045,
  'auc': 0.9632107023411371,
  'accuracy': 0.8979591836734694,
  'f1': 0.9056603773584906}}